apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
    - name: url
      value: "tcp://hqpyyshb:bB38GEf93cPG@driver.cloudmqtt.com:18742"
    - name: qos
      value: 1
    - name: retain
      value: "false"
    - name: cleanSession
      value: "true"
    - name: backoffMaxRetries
      value: "0"
